# Generated by Django 4.0.4 on 2022-06-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('telegram_num', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
