# Generated by Django 4.0.4 on 2022-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_submitted',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
