# Generated by Django 4.0.4 on 2022-06-23 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_date_confirmed_user_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 14, 18, 47, 896860), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 14, 18, 47, 896860)),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='asdasdasd', max_length=512),
            preserve_default=False,
        ),
    ]
