# Generated by Django 4.0.5 on 2022-07-01 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_user_type_alter_user_date_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 2, 2, 1, 2, 196429), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 2, 1, 2, 196429)),
        ),
    ]
