# Generated by Django 4.0.5 on 2022-07-03 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_date_confirmed_alter_user_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 3, 15, 12, 31, 543035), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 12, 31, 543035)),
        ),
    ]
