# Generated by Django 4.0.5 on 2022-07-04 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_date_confirmed_alter_user_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 4, 20, 16, 41, 428135), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 16, 41, 428135)),
        ),
    ]
