# Generated by Django 4.0.4 on 2022-05-31 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.TextField(blank=True, max_length=4096)),
                ('uz', models.TextField(max_length=4096)),
                ('next_question', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Test poll', max_length=512, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 31, 22, 43, 7, 726067))),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 5, 31, 22, 43, 7, 727066))),
                ('user_id', models.IntegerField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.answer')),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz', models.TextField(max_length=4096)),
                ('ru', models.TextField(blank=True, max_length=4096)),
                ('finish', models.BooleanField()),
                ('num', models.IntegerField()),
                ('type', models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('open', 'Open question'), ('location', 'Location'), ('age', 'Age'), ('integer', 'Integer')], max_length=128)),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.poll')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question'),
        ),
    ]
