# Generated by Django 4.0.5 on 2022-06-19 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_question_product_answer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='update_db',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 13, 41, 414255)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 13, 41, 414255)),
        ),
    ]
