# Generated by Django 4.0.5 on 2022-06-19 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_poll_update_db_alter_poll_date_alter_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 47, 0, 302369)),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multiple', 'Multiple choice'), ('open', 'Open question'), ('location', 'Location'), ('integer', 'Integer'), ('image', 'Image'), ('password', 'Password'), ('action', 'Action')], max_length=128),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 47, 0, 302369)),
        ),
    ]
