# Generated by Django 4.0.4 on 2022-06-20 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_alter_poll_date_alter_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openanswer',
            name='answer',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 20, 41, 35, 339505)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 20, 41, 35, 339505)),
        ),
    ]
