# Generated by Django 4.0.4 on 2022-06-20 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_alter_openanswer_answer_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 34, 52, 335599)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 21, 34, 52, 335599)),
        ),
    ]
