# Generated by Django 4.0.4 on 2022-06-21 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_alter_poll_date_alter_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_id_source',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='response',
            name='response_type',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 51, 27, 472370)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 51, 27, 472370)),
        ),
    ]
