# Generated by Django 4.0.4 on 2022-06-21 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_alter_poll_date_alter_response_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='answer_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id_source',
            new_name='answer_id_source',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_type',
            new_name='answer_type',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 56, 51, 746288)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 56, 51, 748416)),
        ),
    ]
