# Generated by Django 4.0.4 on 2022-06-21 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_alter_poll_date_alter_response_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer_id_source',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='response',
            name='date',
        ),
        migrations.RemoveField(
            model_name='response',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 11, 59, 32, 879721)),
        ),
    ]
