# Generated by Django 4.0.4 on 2022-06-21 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_delete_response_alter_poll_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 0, 58, 861500)),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(max_length=512)),
                ('answer_id_source', models.CharField(blank=True, max_length=512)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 0, 58, 861500))),
                ('user_id', models.IntegerField()),
                ('poll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.poll')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.question')),
            ],
        ),
    ]
