# Generated by Django 4.0.4 on 2022-06-21 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_alter_poll_date_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 1, 48, 512316)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 1, 48, 512316)),
        ),
    ]
