# Generated by Django 4.0.4 on 2022-06-21 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_alter_poll_date_alter_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='record_id',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 13, 34, 854863)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 12, 13, 34, 855859)),
        ),
    ]
