# Generated by Django 4.0.4 on 2022-06-22 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_response_record_id_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 16, 54, 44, 937302)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 22, 16, 54, 44, 938300)),
        ),
    ]
