# Generated by Django 4.0.5 on 2022-07-02 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0063_answer_show_users_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='show_users',
        ),
        migrations.AddField(
            model_name='question',
            name='show_users',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 18, 39, 42, 322843)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 18, 39, 42, 322843)),
        ),
    ]
