# Generated by Django 4.0.5 on 2022-07-02 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0064_remove_answer_show_users_question_show_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 20, 7, 23, 577015)),
        ),
        migrations.AlterField(
            model_name='question',
            name='show_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 20, 7, 23, 577015)),
        ),
    ]
