# Generated by Django 4.0.5 on 2022-07-03 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0068_alter_answer_show_users_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='show_users',
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 19, 49, 823510)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 19, 49, 824508)),
        ),
    ]
