# Generated by Django 4.0.5 on 2022-07-03 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0069_remove_answer_show_users_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='show_users',
            field=models.CharField(blank=True, choices=[('show_all_users', 'Show all users'), ('show_confirmed_users', 'Show confirmed users'), ('show_not_confirmed_users', 'Show now confirmed users'), (None, 'None')], default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 20, 10, 353185)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 20, 10, 354183)),
        ),
    ]
