# Generated by Django 4.0.5 on 2022-07-04 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0070_answer_show_users_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='show_users',
            field=models.CharField(blank=True, choices=[('show_all_users', 'Show all users'), ('show_confirmed_users', 'Show confirmed users'), ('show_not_confirmed_users', 'Show not confirmed users'), (None, 'None')], default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 16, 41, 406008)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 16, 41, 406008)),
        ),
    ]
