# Generated by Django 4.0.5 on 2022-07-04 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0071_alter_answer_show_users_alter_poll_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 23, 14, 825443)),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 20, 23, 14, 825443)),
        ),
    ]
