# Generated by Django 4.0.5 on 2022-06-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim')], max_length=512)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('units', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
