# Generated by Django 4.0.5 on 2022-06-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_poll_date_alter_response_date'),
        ('products', '0004_rename_amount_record_quantity_record_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.poll'),
        ),
        migrations.AlterField(
            model_name='record',
            name='units',
            field=models.CharField(choices=[('korobka', 'Korobka'), ('qop', 'Qop')], max_length=512),
        ),
    ]
