# Generated by Django 4.0.5 on 2022-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_identifier_question_product_question_type_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identifier',
            old_name='question',
            new_name='question_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='question',
            new_name='question_ru',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='question',
            new_name='question_ru',
        ),
        migrations.AddField(
            model_name='identifier',
            name='question_uz',
            field=models.TextField(default=0, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='question_uz',
            field=models.TextField(default=0, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='question_uz',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
