# Generated by Django 4.0.4 on 2022-06-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_record_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='units',
            new_name='unit',
        ),
    ]
