# Generated by Django 4.0.4 on 2022-06-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_units_record_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
