# Generated by Django 4.0.4 on 2022-06-21 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_record_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='index',
        ),
    ]
