# Generated by Django 4.0.4 on 2022-06-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_record_id_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='payment',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='quantity',
            new_name='response_id',
        ),
        migrations.RemoveField(
            model_name='record',
            name='action',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='id_source',
        ),
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
        migrations.RemoveField(
            model_name='record',
            name='item',
        ),
        migrations.RemoveField(
            model_name='record',
            name='price',
        ),
        migrations.RemoveField(
            model_name='record',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='record',
            name='volume',
        ),
        migrations.AddField(
            model_name='record',
            name='response_id_source',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='record',
            name='response_type',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
