# Generated by Django 4.0.4 on 2022-06-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_payment_record_question_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
