# Generated by Django 4.0.5 on 2022-07-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='identifier',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
